import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";
import { MobileSidebarProvider } from "@/lib/MobileSidebarContext";
import { ThemeProvider } from "@/lib/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-brand-dark text-brand-cream dark:bg-gray-50 dark:text-gray-900 h-screen flex flex-col transition-colors duration-300`}
      >
        <ThemeProvider>
          <MobileSidebarProvider>
            <NavbarWrapper />
            <div className="flex-1 overflow-y-auto overflow-x-hidden">
              {children}
            </div>
          </MobileSidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
