import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";
import { MobileSidebarProvider } from "@/lib/MobileSidebarContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-brand-dark text-brand-cream h-screen overflow-hidden flex flex-col`}
      >
        <MobileSidebarProvider>
          <NavbarWrapper />
          <div className="flex-1 overflow-hidden">
            {children}
          </div>
        </MobileSidebarProvider>
      </body>
    </html>
  );
}
